import { Merchant, Transaction, Settlement, FraudLog } from './types';

// Helper to generate past dates
const getDateHoursAgo = (hours: number): string => {
  const date = new Date(Date.now() - hours * 60 * 60 * 1000);
  return date.toISOString();
};

export const INITIAL_MERCHANTS: Merchant[] = [
  {
    id: 'mer_01',
    businessName: 'Skyline Retail Ltd',
    ownerName: 'Aravind Sharma',
    mobile: '9876543210',
    email: 'aravind@skylineretail.in',
    gstNumber: '27AAAAA1111A1Z1',
    panNumber: 'ABCDE1234F',
    bankAccount: '918273645019',
    bankName: 'HDFC Bank',
    ifscCode: 'HDFC0000124',
    upiId: 'skylineretail@hdfc',
    status: 'Active',
    apiKey: 'pk_live_51Msk72HnZjl23oAp89wXyz10qp90b76z',
    webhookUrl: 'https://api.skylineretail.in/webhooks/upi',
    createdAt: getDateHoursAgo(360), // 15 days ago
    kycSubmitted: true,
    kycApprovedAt: getDateHoursAgo(350),
  },
  {
    id: 'mer_02',
    businessName: 'Nova Foodtech Essentials',
    ownerName: 'Priya Patel',
    mobile: '8765432109',
    email: 'priya@novafoodtech.com',
    gstNumber: '24BBBBB2222B2Z2',
    panNumber: 'FGHIJ5678K',
    bankAccount: '112233445566',
    bankName: 'ICICI Bank',
    ifscCode: 'ICIC0000392',
    upiId: 'novafoodtech@icici',
    status: 'Active',
    apiKey: 'pk_live_38Js92KdMwq82nPp10xAtz58qb90z55x',
    webhookUrl: 'https://novafoodtech.com/payments/callback',
    createdAt: getDateHoursAgo(240), // 10 days ago
    kycSubmitted: true,
    kycApprovedAt: getDateHoursAgo(230),
  },
  {
    id: 'mer_03',
    businessName: 'Apex Services & Digital Co',
    ownerName: 'Vikram Singh',
    mobile: '7654321098',
    email: 'vikram@apexservices.co.in',
    gstNumber: '09CCCCC3333C3Z3',
    panNumber: 'LMNOP9012Q',
    bankAccount: '556677889900',
    bankName: 'State Bank of India',
    ifscCode: 'SBIN0000843',
    upiId: 'apexco@sbi',
    status: 'Pending',
    apiKey: 'pk_live_49La03XmKst92oOq39zAzk47qc78c43z',
    webhookUrl: '',
    createdAt: getDateHoursAgo(12), // 12 hours ago
    kycSubmitted: true,
    kycApprovedAt: null,
  },
  {
    id: 'mer_04',
    businessName: 'Nebula Sol Software Agency',
    ownerName: 'Rohan Gupta',
    mobile: '6543210987',
    email: 'rohan@nebulasol.io',
    gstNumber: '07DDDDD4444D4Z4',
    panNumber: 'RSTUV3456W',
    bankAccount: '998877665544',
    bankName: 'Axis Bank',
    ifscCode: 'UTIB0000030',
    upiId: 'nebulasol@axis',
    status: 'Suspended',
    apiKey: 'pk_live_82Nz41YvPqw93mUn18aSzk19qa10p98y',
    webhookUrl: 'https://nebulasol.io/api/upi-webhooks',
    createdAt: getDateHoursAgo(480), // 20 days ago
    kycSubmitted: true,
    kycApprovedAt: getDateHoursAgo(470),
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_101',
    merchantId: 'mer_01',
    merchantName: 'Skyline Retail Ltd',
    customerName: 'Suresh Kumar',
    amount: 1499.00,
    upiId: 'sureshkumar@okaxis',
    paymentMethod: 'UPI Intent',
    status: 'Success',
    createdAt: getDateHoursAgo(1.5),
    riskScore: 8,
    riskAnalysis: 'Standard consumer transaction from trusted device. Location matches typical usage.',
    isRefunded: false,
    refundedAt: null,
  },
  {
    id: 'tx_102',
    merchantId: 'mer_02',
    merchantName: 'Nova Foodtech Essentials',
    customerName: 'Ananya Roy',
    amount: 350.00,
    upiId: 'ananya@okicici',
    paymentMethod: 'QR Code',
    status: 'Success',
    createdAt: getDateHoursAgo(2.1),
    riskScore: 12,
    riskAnalysis: 'Low-value grocery payment. Fully validated dynamic QR code.',
    isRefunded: false,
    refundedAt: null,
  },
  {
    id: 'tx_103',
    merchantId: 'mer_01',
    merchantName: 'Skyline Retail Ltd',
    customerName: 'Mukesh Ambani',
    amount: 25000.00,
    upiId: 'mukesh@okhdfc',
    paymentMethod: 'Collect Request',
    status: 'Processing',
    createdAt: getDateHoursAgo(0.2),
    riskScore: 42,
    riskAnalysis: 'Higher transaction amount. Requiring typical OTP/UPI pin submission verification.',
    isRefunded: false,
    refundedAt: null,
  },
  {
    id: 'tx_104',
    merchantId: 'mer_04',
    merchantName: 'Nebula Sol Software Agency',
    customerName: 'Vikranth Reddy',
    amount: 8500.00,
    upiId: 'vikreddy@okaxis',
    paymentMethod: 'UPI ID',
    status: 'Failed',
    createdAt: getDateHoursAgo(5.4),
    riskScore: 78,
    riskAnalysis: 'High risk rating detected. IP address blacklisted for spamming. Decrypted header mismatched.',
    isRefunded: false,
    refundedAt: null,
  },
  {
    id: 'tx_105',
    merchantId: 'mer_01',
    merchantName: 'Skyline Retail Ltd',
    customerName: 'Ritu Phogat',
    amount: 4999.00,
    upiId: 'rituphogat@paytm',
    paymentMethod: 'QR Code',
    status: 'Success',
    createdAt: getDateHoursAgo(8.2),
    riskScore: 15,
    riskAnalysis: 'Authentic mobile payment via Paytm static merchant QR.',
    isRefunded: false,
    refundedAt: null,
  },
  {
    id: 'tx_106',
    merchantId: 'mer_02',
    merchantName: 'Nova Foodtech Essentials',
    customerName: 'Gaurav Sen',
    amount: 1250.00,
    upiId: 'gaurav@okaxis',
    paymentMethod: 'UPI Intent',
    status: 'Success',
    createdAt: getDateHoursAgo(12.5),
    riskScore: 5,
    riskAnalysis: 'Seamless checkout via Google Pay intent. Fast response.',
    isRefunded: true,
    refundedAt: getDateHoursAgo(10.0),
  },
  {
    id: 'tx_107',
    merchantId: 'mer_01',
    merchantName: 'Skyline Retail Ltd',
    customerName: 'Arjun Kapoor',
    amount: 18500.00,
    upiId: 'arjun@ybl',
    paymentMethod: 'Collect Request',
    status: 'Failed',
    createdAt: getDateHoursAgo(16.0),
    riskScore: 92,
    riskAnalysis: 'Flagged by Fraud Detection Engine. Rapid serial requests from multiple IPs within 2 minutes.',
    isRefunded: false,
    refundedAt: null,
  },
  {
    id: 'tx_108',
    merchantId: 'mer_02',
    merchantName: 'Nova Foodtech Essentials',
    customerName: 'Sandhya Rao',
    amount: 180.00,
    upiId: 'sandhya@sbi',
    paymentMethod: 'QR Code',
    status: 'Success',
    createdAt: getDateHoursAgo(20.0),
    riskScore: 4,
    riskAnalysis: 'Low-risk retail scan, standard fast completion.',
    isRefunded: false,
    refundedAt: null,
  },
  {
    id: 'tx_109',
    merchantId: 'mer_01',
    merchantName: 'Skyline Retail Ltd',
    customerName: 'Kabir Dev',
    amount: 950.00,
    upiId: 'kabir@okicici',
    paymentMethod: 'UPI Intent',
    status: 'Success',
    createdAt: getDateHoursAgo(28.0),
    riskScore: 10,
    riskAnalysis: 'Validated standard checkouts.',
    isRefunded: false,
    refundedAt: null,
  },
  {
    id: 'tx_110',
    merchantId: 'mer_01',
    merchantName: 'Skyline Retail Ltd',
    customerName: 'Meghna Nair',
    amount: 7200.00,
    upiId: 'meghna@okhdfc',
    paymentMethod: 'UPI ID',
    status: 'Success',
    createdAt: getDateHoursAgo(32.0),
    riskScore: 24,
    riskAnalysis: 'High amount but customer profile matches typical premium basket.',
    isRefunded: false,
    refundedAt: null,
  },
  {
    id: 'tx_111',
    merchantId: 'mer_02',
    merchantName: 'Nova Foodtech Essentials',
    customerName: 'Aditya Birla',
    amount: 450.00,
    upiId: 'aditya@paytm',
    paymentMethod: 'QR Code',
    status: 'Success',
    createdAt: getDateHoursAgo(44.0),
    riskScore: 3,
    riskAnalysis: 'Fast QR swipe.',
    isRefunded: false,
    refundedAt: null,
  },
  {
    id: 'tx_112',
    merchantId: 'mer_01',
    merchantName: 'Skyline Retail Ltd',
    customerName: 'Deepak Chahar',
    amount: 3200.00,
    upiId: 'deepak@okaxis',
    paymentMethod: 'UPI ID',
    status: 'Failed',
    createdAt: getDateHoursAgo(52.0),
    riskScore: 61,
    riskAnalysis: 'Expired collect request timer, user did not approve in time.',
    isRefunded: false,
    refundedAt: null,
  },
  {
    id: 'tx_113',
    merchantId: 'mer_02',
    merchantName: 'Nova Foodtech Essentials',
    customerName: 'Zoya Khan',
    amount: 1100.00,
    upiId: 'zoyakhan@ybl',
    paymentMethod: 'UPI Intent',
    status: 'Success',
    createdAt: getDateHoursAgo(72.0),
    riskScore: 14,
    riskAnalysis: 'Standard verified client login from mobile App.',
    isRefunded: false,
    refundedAt: null,
  },
];

export const INITIAL_SETTLEMENTS: Settlement[] = [
  {
    id: 'set_201',
    merchantId: 'mer_01',
    merchantName: 'Skyline Retail Ltd',
    amount: 18500.00,
    bankAccount: '918273645019',
    upiId: 'skylineretail@hdfc',
    status: 'Completed',
    requestedAt: getDateHoursAgo(48),
    settledAt: getDateHoursAgo(44),
    utr: 'UTR829302839049',
  },
  {
    id: 'set_202',
    merchantId: 'mer_02',
    merchantName: 'Nova Foodtech Essentials',
    amount: 4500.00,
    bankAccount: '112233445566',
    upiId: 'novafoodtech@icici',
    status: 'Completed',
    requestedAt: getDateHoursAgo(36),
    settledAt: getDateHoursAgo(30),
    utr: 'UTR839402930193',
  },
  {
    id: 'set_203',
    merchantId: 'mer_01',
    merchantName: 'Skyline Retail Ltd',
    amount: 11498.00,
    bankAccount: '918273645019',
    upiId: 'skylineretail@hdfc',
    status: 'Pending',
    requestedAt: getDateHoursAgo(6),
    settledAt: null,
    utr: null,
  },
  {
    id: 'set_204',
    merchantId: 'mer_02',
    merchantName: 'Nova Foodtech Essentials',
    amount: 1600.00,
    bankAccount: '112233445566',
    upiId: 'novafoodtech@icici',
    status: 'Pending',
    requestedAt: getDateHoursAgo(3),
    settledAt: null,
    utr: null,
  },
];

export const INITIAL_FRAUD_LOGS: FraudLog[] = [
  {
    id: 'fr_301',
    ipAddress: '103.241.12.89',
    device: 'OPPO F19 - Android 12',
    merchantName: 'Skyline Retail Ltd',
    amount: 18500.00,
    riskRating: 'Critical',
    reason: 'Mass spamming pattern. 5 distinct failed collect authorizations within 90 seconds.',
    createdAt: getDateHoursAgo(16),
    location: 'Mumbai, Maharashtra',
  },
  {
    id: 'fr_302',
    ipAddress: '198.162.2.140',
    device: 'Unknown Device - Linux Browser',
    merchantName: 'Nebula Sol Software Agency',
    amount: 8500.00,
    riskRating: 'High',
    reason: 'IP blacklisted in cloud security audits. VPN connection proxy detected.',
    createdAt: getDateHoursAgo(5.4),
    location: 'Bangalore, Karnataka',
  },
  {
    id: 'fr_303',
    ipAddress: '122.180.99.3',
    device: 'Redmi Note 10 - Android 11',
    merchantName: 'Skyline Retail Ltd',
    amount: 25000.00,
    riskRating: 'Medium',
    reason: 'High transaction value initiated from an unusual geolocated coordinates cluster.',
    createdAt: getDateHoursAgo(0.2),
    location: 'Gurugram, Haryana',
  },
  {
    id: 'fr_304',
    ipAddress: '49.206.120.40',
    device: 'Chrome v102 - MacOS 11',
    merchantName: 'Nova Foodtech Essentials',
    amount: 1250.00,
    riskRating: 'Low',
    reason: 'Mismatched device fingerprint headers, but verified customer history overrides alert levels.',
    createdAt: getDateHoursAgo(12.5),
    location: 'Pune, Maharashtra',
  },
];
